import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Aydin',
      email: 'aydindereci@hotmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Serkan',
      email: 'serkankutludag@gmail.com',
      password: bcrypt.hashSync('654321'),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: 'W31 Mariner',
      slug: 'w31-mariner',
      category: 'Screw Compressors',
      image: '/images/w31mariner.png',
      brand: 'Alkin',
      hp: '13',
      features: 'Auto Shutoff',
      price: 10000,
      countInStock: 30,
      description: '123123',
    },
    {
      name: 'W32 Mariner',
      slug: 'w32-mariner',
      category: 'Screw Compressors',
      image: '/images/w32mariner.png',
      brand: 'Alkin',
      hp: '15',
      features: 'Auto Shutoff',
      price: 10000,
      countInStock: 5,
      description: '123123',
    },
    {
      name: '524 Canopy',
      slug: '524-canopy',
      category: 'Screw Compressors',
      image: '/images/526canopy.png',
      brand: 'Alkin',
      hp: 20,
      features: 'Auto Shutoff',
      price: 10000,
      countInStock: 3,
      description: '123123',
    },
    {
      name: '526 Canopy',
      slug: '526-canopy',
      category: 'Screw Compressors',
      image: '/images/526canopy.png',
      brand: 'Alkin',
      hp: 22,
      features: 'Auto Shutoff',
      price: 10000,
      countInStock: 10,
      description: '123123',
    },
    {
      name: '527 Diesel',
      slug: '527-diesel',
      category: 'Screw Compressors',
      image: '/images/527diesel.png',
      brand: 'Alkin',
      hp: 22,
      features: 'Auto Shutoff',
      price: 10000,
      countInStock: 20,
      description: '123123',
    },
    {
      name: '700 Chassis',
      slug: '700-chassis',
      category: 'Screw Compressors',
      image: '/images/700chassis.png',
      brand: 'Alkin',
      hp: 22,
      features: 'Auto Shutoff',
      price: 10000,
      countInStock: 3,
      description: '123123',
    },
  ],
};

export default data;
